{% set version = "1.0.2" %}
{% set sha256 = "965d4b8d0c5a13fd85db8e978582c071b4545d37c86503ca851c56449db22463" %}

package:
  name: nc_time_axis
  version: {{ version }}

source:
  fn: nc-time-axis-{{ version }}.tar.gz
  url: https://github.com/SciTools/nc-time-axis/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - matplotlib
    - netcdf4 >=1.1
    - numpy

test:
  imports:
    - nc_time_axis

about:
  home: https://github.com/SciTools/nc-time-axis
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Support for netcdftime axis in matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
    - lbdreyer
