{% set version = "1.0.0" %}

package:
  name: nc_time_axis
  version: {{ version }}

source:
  fn: nc-time-axis-{{ version }}.tar.gz
  url: https://github.com/SciTools/nc-time-axis/archive/v{{ version }}.tar.gz
  sha256: d6a2a7d1e1b1aa3a1440f2d71e361f8f359155faf830b2884f069111bfc79dba

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - six
    - matplotlib
    - netcdf4 >=1.1
    - numpy

test:
  imports:
    - nc_time_axis

about:
  home: https://github.com/SciTools/nc-time-axis
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Support for netcdftime axis in matplotlib.'

extra:
  recipe-maintainers:
    - ocefpaf
    - lbdreyer
