{% set version = "1.1.0" %}
{% set sha256 = "51e8452ad0e7fb4a5eed6588880d8d2a6b3a23a6d111aa203bf2ff127bbe4a1f" %}

package:
  name: nc_time_axis
  version: {{ version }}

source:
  fn: nc-time-axis-{{ version }}.tar.gz
  url: https://github.com/SciTools/nc-time-axis/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cftime
    - matplotlib
    - numpy
    - six

test:
  imports:
    - nc_time_axis

about:
  home: https://github.com/SciTools/nc-time-axis
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Provides support for non-gregorian datetimes in matplotlib based on the cftime package'

extra:
  recipe-maintainers:
    - lbdreyer
    - ocefpaf
    - pelson
