{% set version = "1.2.0" %}

package:
  name: nc-time-axis
  version: {{ version }}

source:
  url: https://github.com/SciTools/nc-time-axis/archive/v{{ version }}.tar.gz
  sha256: 2fae9b904a5284581aa8ac1fd954776fc246339665411724b23d0e3b4449332f

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - cftime
    - matplotlib-base
    - numpy
    - six

test:
  imports:
    - nc_time_axis

about:
  home: https://github.com/SciTools/nc-time-axis
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Provides support for a cftime axis in matplotlib

extra:
  recipe-maintainers:
    - lbdreyer
    - ocefpaf
    - pelson
    - bjlittle
