travis:
  secure:
    BINSTAR_TOKEN: oh4lGYdrAgtPIUrGzn1i4m87KAYGVDyPM/+6w2qsx31Dfu316Xv5/+A3G0E/Ct5zEfQrAifCMWDdmxX6UlOq5J3P47WmDfS1KlP1Dvnmc2gObe8uoR8QLYo6sIrPD+Iqm/6WL64jR4tR6Cb4zAK87nHtTj1uc35Ie88aiEC4MPDqPMVrhLJRZ244jAl9WE//0RpNDTqvqjklBm5duAIpBRzLlaDSGf8gH47NgralWM3r60MCQNH4TRkIw7wRSEZuH4utLCtjG9sC0GOZDS2s0/5JoC6cWZSH3NKaBUHwUOOHhRFLSUfh/fRnFmiVMwO64O2kfNvzA1DG0Pmdz8qjU47Qsg+YZtSYCbvLIEiqcH+Xh2q96Y1yZ8h++u8KS735b3Pte5WDO21ap8tQ+/1fxt4k0lnPWZUx0pl1a7vT2eiYiFn5LGxQ3WextxbiHqSF6xpaKSDLiezBAxh9unTckCBgskSMpAMQ+MFfY7Dnfet35S9JsgkihPV/4QHG3COlyTd7GriRsjIMYLFJ3mAcf9ko2Gvrr6D0xfIdLv/mQ/Dq+KWVT4O+CTXtL8FnZHDFFPIx97+y8ILmmxpMnZQ32cbAgxNVJCBwZVa27PwjTTLTkRYba7rQLiw4Xdsx2hI76bfE+oDxaXT/wJEF9QlbuJ17x9kqdZKkHJTwqGVFyNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
