travis:
  secure:
    BINSTAR_TOKEN: RCYtyymHXecsNfiv9MFCOne6BOm3pYirZ8TdkN8ln4Owk7sd1XNaVdZn53c6L/2j7RSweef4bt949b/X7nK8itabsUbtQ/QKZKNQVSizw79s/omcjCRgKVEOsOOTs4l2ao1AP6TLkQTqYEdgCcS25gfw56ESljN9Yr1H43dXh1PMyC4hnVN6pz3cm5sRzuIggnSTrNR7z+vyf/heAXGVgPlPRIdTtg6qgQu3KyKKa4N+YikUvLHz/xaGLYx6clLNSYSFmNE/ru+iU/RqP14FnmUTLCA71PzuAm8ah/NmR+8StT2nsW/XukTZXineHVdoNHRQNatd656fIp7h3kAqK5v5kcEdI4VN/i79XcQZoX6kSP0c1Pyqfh2YFbTLvGuCFBt3cXV9+uz9S5uqUyiThvtXJs0y+wv4LmvVf7fsau2fHXBLqAS4BA3AwBL/gejLeqCW+OJz0OTBF6Gp40fb6r0fSCQUa9SHgoMcQ0MxT/0BCT/XzRsS9QnP+0jVx9p8n9k2THy9pIOuYI82/g4fICykDCNhc6uxHkXJXZIucf8FF1QNz/c5QDUXU+bCcQ/YRqcfn70AwUJ8WGCopT108P7xqnLAJKPe20T0HD4zr9o9OUb3gmo/37I/7wv59rYIdpTsFr8JwgPm2rLlJkCTtTo+Ss9mO016QB0rugJKwtU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
