travis:
  secure:
    BINSTAR_TOKEN: rG1d3mTtR0P7qqFKyXSz13naRgQDIadYpicPmzrpq5P7VJ6ef1HsrYqr55xjRduP6ldFf+f8OKd2ZCrBEp30Z7wVVKL97OKROHPBIIBFUQr55hom3owNi1jToHjxCM9JwzJKwK32M1mo0AcS4nbGORvEVUR3efFfnqz6pVNuul+xi/P3IgxFXJNHRiLcC7i1Htf9CNrS5sKEuNt3H9dF38aCHjTkz38moZI+cIDBBxwPsr7EoOOeo3kFpuGO74Br482DHmgPZmoMP85png6+yxwiW3DXnsbkquYWHNNQehM+eWe2AD4ezkemqCiq7dhwglyo149+j/XJKWdknDy/4RTu8keDruB08dzgFH9AmtQtddyRLTObTqnwiID3SYCThWuuee5zrIsZcbN9NYKkXqgV2eWgFvaG7mI8e47+ehVvfNCjknsCsRpqxpylXt4v95nw3XbDl1t5DOvyyMw5cXBm5xdVfogwvJi6Z5bSWtrzZpHGamObuOQ5zA/G041BpIgLv57Z2QrbeQDsgQUh11PWOsx5LnmdpzOt2d2wU+Ffk+06QhvGJYJ/z0SlPuqP0F7Ue/TQrwJNZNRJ1sqjEaSZc6Qo4KAiKtddmMnZ70d2JK0Wd3AXvju/28Da6PwR/EV3YxQqnzLasd7tPa8iVcavMaCp7dLNMKENsY9sPFI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
